### ISSUE TITLE
[TODO] Create some logging

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#16]
We now have morgan and winston installed on the server.

These are loggers.

Save server logs to /src/server/logs/

They wont be pushed to github for obv reasons but we should always do logging.

**Comment by jzunigarce** [comment]
Assign it to me

**Comment by gbowne1** [comment]
Tomorrow morning I can show examples of wiring up both morgan and winston so they work together.  One is for HTTP requests and we should use both.

**Comment by gbowne1** [comment]
This would be something like this:


```js
const winston = require('winston');
const morgan = require('morgan');

const logger = winston.createLogger({
  transports: [
    new winston.transports.Console({
      level: 'debug',
      handleExceptions: true,
      json: false,
      colorize: true
    }),
    new winston.transports.File({
      level: 'info',
      filename: './logs/all-logs.log',
      handleExceptions: true,
      json: true,
      maxsize: 5242880, // 5MB
      maxFiles: 5,
      colorize: false
    })
  ],
  exitOnError: false
});

logger.stream = {
  write: function(message, encoding) {
    logger.info(message.trim());
  }
};

app.use(morgan('combined', { stream: logger.stream }));
```

**Comment by jzunigarce** [comment]
I'm going to configure winston to replace the console.logs and also created a module to handle morgan. I will stop the middleware in another file to make the server.js a bit cleaner

**Comment by gbowne1** [comment]
I actually like that idea and actually was headed that direction with some thoughts I had.

I will push up the initial work I did with the README.md and the TODO.md replacing a bunch of the Issues.  We should use that for stuff we need to get done.

**Comment by gbowne1** [comment]
I tested this this afternoon.  It does create some good logs.  Very useful

**Comment by jzunigarce** [comment]
Can we meet on a video call to go over some details?

**Comment by gbowne1** [comment]
Like what? I still have plenty to document and work on.  You can always use Discussion tab for conversation about the project, that are separate from an issue.

**Comment by gbowne1** [comment]
Closed as completed.
