### ISSUE TITLE
[BUG] The dashboard.html has CORS issues with CDN libraries

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#19]
The dashboard.hml now has CORS issues possibly coming from the headers set in the server.js or in the html itself.

Our policy must be blocking the headers coming from Cloudflare CDN.

We really should be using downloaded resources in the client (bootstrap, font-awesome, popperjs , jQuery, etc.) but wanted to use CDN's in the development phase of this project.  

I'm not a CORS expert, nor an ExpressJS expert.  The browser console when navigated to /dashbord has some significant issues.

**Comment by jzunigarce** [comment]
I fix the issue, i will not upload it yet because the external images do not load.  Regarding the logo, did you upload it?

**Comment by gbowne1** [comment]
No I did not upload the logo. @jzunigarce

**Comment by gbowne1** [comment]
I think this is largely fixed now correct @jzunigarce?
