### ISSUE TITLE
[TODO] Fix image links in /dashboard 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#20]
Fix the images links in the dashboard to the images in /src/client/public/img instead of the image placeholder link.

the path to dashboard is /src/client/public/dashboard/dashboard.html

**Comment by Phil94comp** [comment]
For the image links on lines 45, 92, 100, 108, 116, 124, 132, and 140 in the dashboard.html file does it matter which images from the img file are used? If so can you please tell me which images from the img folder you want to replace the image placeholder links?

**Comment by gbowne1** [comment]
the image should be sized to 200x200.

@Phil94comp 

There should be cards labeled:

- Ham Log (uses radio_01.jpg)
- SWL Log (uses swraido.jpg)
- Scan Log (uses bc250.jpg)
- VHF Log (have not decided on image)
- MW Log (uses mwradio.jpg)
- Contest Log (have not decided on image)
- two more cards, might be labeled Rig Control and QSL Database.  (have not decided on image(s).

I have not decided on images or names of the last 2 cards.

**Comment by jzunigarce** [comment]
Consider using static route for images in html templates

**Comment by gbowne1** [comment]
Yeah, CORS is blocking all the assets now though.  Try /dashboard and look at the console.

**Comment by jzunigarce** [comment]
I can fix the link of assets in the dashboard, can you assign me the bug?

**Comment by gbowne1** [comment]
I fixed some of it with helmet.  Did some reading on CORS and  Will push some changes.
