### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#29]
I am still getting The resource from “http://localhost:3000/src/client/public/css/login.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). while on the /login route

Also getting Uncaught SyntaxError: redeclaration of const registerTab from tabs.js

**Comment by gbowne1** [comment]
I'm pretty sure this is a CORS issue.  I have no idea what tabs.js does for sure.  It was a remnant from a previous iteraton of the project, but it was wired up by script tag so I tossed it in.

**Comment by jzunigarce** [comment]
For access to the assets, i set the paths from the public folder.
![image](https://user-images.githubusercontent.com/722001/233836369-338888b4-836d-47b4-8c0d-d9f2ffb93e18.png)
![image](https://user-images.githubusercontent.com/722001/233836550-95a4c3c8-96cc-4d05-b8f5-688276a23a36.png)

**Comment by gbowne1** [comment]
Cool.   I will look when I get back.  Looks good so far.
More issues in the TODO.md

**Comment by gbowne1** [comment]
Hmm.. that's not right. Path to login.css should be /src/client/public/css/login.css on the server, not /css/login.css.. but since we are serving from /public/..  yeah.

It still 404's as well as does a MIME Type Mismatch... assuming its talking about a path error.

**Comment by jzunigarce** [comment]
The path is because i configure that from the /public folder. CAn you show an example of the error?

**Comment by gbowne1** [comment]
navigated to localhost:3000/login  I get this in console:

The resource from “http://localhost:3000/src/client/public/css/login.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by jzunigarce** [comment]
Change the href attr of the login.css in the file login.html, `href='/css/login.css'`

**Comment by gbowne1** [comment]
Yeah that did it. 100%.  

Edit: fixed and pushed.
