### ISSUE TITLE
Duplicate name file

### ISSUE THREAD

**Issue by jzunigarce** [gbowne1/RadioLogger#37]
The client/public/js folder have two file with same name  signUp.js and signup.js. We should homologate in a single file
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/722001/234385122-5b475f85-b734-4446-87af-becbfd9fd931.png">

**Comment by gbowne1** [comment]
I agree. @jzunigarce   These were both remnants of previous attempts at this project, so, I dont know which file actually works or if we need a new file.

**Comment by AlexVCS** [comment]
Hi there, I'd like to work on this issue. Can you assign it to me please?

**Comment by gbowne1** [comment]
Ok, @AlexVCS.

**Comment by AlexVCS** [comment]
So I should just put the contents of the two files into one file? Is signUp.js the preferred name if so?

**Comment by gbowne1** [comment]
That is the way it is named in the login.html file.  It won't work if you just copy the contents of the other file into one of them. You'll have to test to see if signUp actually works when the app is running.

**Comment by jzunigarce** [comment]
I am currently working on the login functionalities in the backend

**Comment by gbowne1** [comment]
I tried with testuser@example.com (as example.com could be wired in till we get full backend up incl. database) and generated password.  No go, no matter what I tried.  It should even give you some visual indicators of success or failure to the user as an alert, toast, popper, etc.  all of which Bootstrap has built in now. (Popperjs is deprecated now.)

**Comment by AlexVCS** [comment]
I cloned the project and installed the dependencies in the client server directories(npm i). Are there test credentials for me to put into my .env?

**Comment by gbowne1** [comment]
@AlexVCS you can put any boolean value into SESSION_SECRET= in the .env

You will also need:

```shell
MONGODB_URI=mongodb://username:password@host:port/database
PORT=3000
```

**Comment by jzunigarce** [comment]
The values of .env are:
![image](https://user-images.githubusercontent.com/722001/234426712-36138621-9714-42fd-bad6-22926acbd3e0.png)
You can add whatever value you want for the port, host and secret

**Comment by AlexVCS** [comment]
Thanks. I tried adding what you both mention but keep getting errors when trying to run the app. 

This is what the file looks like after your recommendations:

```
MONGODB_URI=mongodb://username:password@host:port/database
PORT=4000
HOST=2000
SESSION_SECRET=true
```

I can run the client or the server but not both at the same time. It says secret option required for sessions. Do I need a mongo username and pw?

**Comment by gbowne1** [comment]
You have to start mongod and the cd to src/server and start the server.  Client and server I have on the same port.
It works fine. I have not needed to run the client.  Then go to your browser and go to localhost:3000.  That is the native port and is set elsewhere in the code.

Make sure that its MONGO_PORT and MONGO_HOST not just port and host.

Set up mongodb with db named radiologger and whatever username and password you like.

**Comment by AlexVCS** [comment]
Ok when you say set up mongodb what do you mean? Create a cluster?

**Comment by gbowne1** [comment]
No. Just install Mongodb and create a user, password and create a db called radiologger.

Start mongod which is its server with the command mongod and then cd to src/server and then npm start.  Then go to your browser and go to localhost:3000

**Comment by gbowne1** [comment]
Still not able to login, or redirect to dashboard aftee successful register or login. Although, it gives an array in console.

Theres no login database.

**Comment by jzunigarce** [comment]
Have you already registered user account? you can use postman for call the endpoint register.
Can you share the error that the console shows you?

**Comment by gbowne1** [comment]
yes I registered testuser, password testpass, email testuser@example.com  

I like using example.com which can legally be hard wired as it is an official testing TLD (top level domain) and it may return a result. 

I did not get any error.  

I haven't used postman yet.

**Comment by jzunigarce** [comment]
So your problem is the login, you can't redirect to the dashboard?

**Comment by gbowne1** [comment]
yes.  There is also no thing to show the user login success or even an error.  They would have to look at the console.  I look at it from a users perspective.  

There should be some form of toast, popper, alert, snackbar.. something to show the user that it either passed or failed.

**Comment by jzunigarce** [comment]
We can use https://sweetalert2.github.io/ or alert of bootstrap

**Comment by gbowne1** [comment]
yes I would prefer Alert from native bootstrap, and Alert is good anyhow.

**Comment by gbowne1** [comment]
Will work on the original issue ASAP but there is a duplicate so closing this one.
