### ISSUE TITLE
[TODO] Fix the User Icon menu so that is visible and includes icons

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#5]
We used Bootstrap 5 and Font Awesome for this project.  No more libraries need to be added to this.

The User Icon menu in the dashboard.html is only partially visible when you click on the User Icon in the TopBar/TopNav.

This currently includes a Profile, Settings and Logout.

There are currently no icons next to the labels.

There are no routes to take the user to the respective page of the view.

The Logout button should log the user out, destroy the session, etc and change the button, icon and its label to Login.  The login route is /login and there are login.html, login.js and login.css files to go with the Login.

There are no styles applied to the icon.   

Some of the file paths changed with the new code and repository.   The paths will have to be debugged so that all the HTML, CSS and JS loads to the browser.

**Comment by k-deepak04** [comment]
unable to locate and open the files and see the dashboard. only this is i can see
![Screenshot (190)](https://user-images.githubusercontent.com/96341431/232287329-e14d7ec7-25f0-4cd4-a7de-c33d6dd92392.png)

**Comment by gbowne1** [comment]
@k-deepak04 

The apps dashboard is in: 

/src/client/public/dashboard/dashboard.html

**Comment by gbowne1** [comment]
It should currently look something like ![Screenshot 2023-04-16 at 12-44-20 Radio Logger](https://user-images.githubusercontent.com/47549872/232338386-ea519bd5-8257-44a6-a3a6-0959c746f5df.png)

I made a discussion with a pic of the model I used for the design.

**Comment by gbowne1** [comment]
@k-deepak04 

I did some testing.  I am pretty sure that this is because there are no routes in the server.js file.

**Comment by jzunigarce** [comment]
Will you add all routes?

**Comment by gbowne1** [comment]
@jzunigarce 

I should be able to.  I still have all of the old files. Anyone could add them though.  I listed the routes in one of the other issues.

I will add a couple locally and test.

**Comment by jzunigauabcs** [comment]
Do you have any project settings and styles document?  I can help with some issues

**Comment by gbowne1** [comment]
@jzunigarce 

No there is no style guide yet.  I appreciate any help you can work on. Its currently overnight and I wont get to my pc for another 9 hours from now.

**Comment by gbowne1** [comment]
Routes are: 

/swllog, /vhflog, /mwlog, /dashboard, /hamlog, /scanlog, /qsl and whatever api, login/register or signup/signin routes need to be added too.

**Comment by gbowne1** [comment]
@jzunigarce @jzunigauabcs 

I just now fixed the /src/server/server.js.

 It should work now. I still need to add the pages to go with the routes.

**Comment by jzunigarce** [comment]
Are you returning static pages from the client/public folder?
The .html files will be modified directly or you will use some framework to compile

**Comment by gbowne1** [comment]
@jzunigarce @jzunigauabcs 

yeah the html won't change at all.  All of the html files are basically forms to enter data into the database as well as view data coming back from internal and external apis as well as the database(s) as tables.

Other than the /dashboard and the /profile.  

I am gonna open a discussion in Discussions tab showing features, etc.   Clicking on the dashboard buttons will change the routes.

**Comment by gbowne1** [comment]
Oh and am not using a Framework (React, Angular, Vue, etc. etc.).  Only needed FontAwesome and Bootstrap, PopperJS and jQuery for this.  Node and Express will work just fine.

**Comment by jzunigarce** [comment]
I work with the assets, i can help you fix the menu

**Comment by gbowne1** [comment]
Ok. Great @jzunigarce

**Comment by jzunigarce** [comment]
This is the correct position of submenu?
![Captura desde 2023-04-22 01-24-17](https://user-images.githubusercontent.com/722001/233772671-3c746b0f-1283-492b-920c-2a4930372087.png)

**Comment by gbowne1** [comment]
Yes.

**Comment by gbowne1** [comment]
The actual layout is in Discussions.

**Comment by gbowne1** [comment]
Profile and Settings in that menu get their own route

/profile and /settings..

I havent made those components yet.  Likely that they will be modal.
