### ISSUE TITLE
[BUG] Some pages have CORS errors still

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#53]
Navigating to /dashboard then clicking on the button to each of the pages from the card(s) shows that some of the html files like scanlog.html give CORS errors to the jquery, font-awesome, bootstrap and popperjs libraries.

We should consider downloading and these libraries on the client side package.json in the future and removing the CDN links

The other pages that are experiencing this are:

- hamlog.html
- swllog.html

**Comment by jzunigarce** [comment]
I can correct the links on each of the pages, but the error occurs, for example, in bootstrap because you are using different CDNs and different versions. In the dashboard page you use version 5.2 of cdnjs.cloudfrare and in hamlog you use version 5.2.3 of https://cdn.jsdelivr.net/

**Comment by jzunigarce** [comment]
The url of page are localhost:3000/page. Example: http://localhost:3000/hamlog/, http://localhost:3000/contestlog.
If any route is missing please let me know, the idea is to define the routes in the router folder and not in server.js

**Comment by gbowne1** [comment]
I am goimg to fix the CDNs today.

We should actually be using downloaded assets instead of CDNs but will fix those today.

**Comment by gbowne1** [comment]
I think my push today should fix most of them.  I cleaned up the link tags and script tags using the working ones from the dashboard.html

**Comment by gbowne1** [comment]
Closing this as fixed
