### ISSUE TITLE
[TODO] TODO (See TODO.md)

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#9]
Need to add a logger.

app.use(logger); as a middleware function to add logging to the NodeJS and ExpressJS sever and application.
morgan is already installed on the serverso we will use that as a logger.

I also installed helmet.  This is a middleware tool to help protect  our server from some well-known web vulnerabilities by setting HTTP response headers appropriately. It comes with a collection of several middleware functions that set security headers returned from our Express application

**Comment by jzunigarce** [comment]
I can help you

**Comment by gbowne1** [comment]
Ok @jzunigarce

**Comment by jzunigarce** [comment]
Did the middleware implementations work for you?

**Comment by gbowne1** [comment]
Havent tested yet.  Everything I've read says this is the way to go and we are still getting stuff set up.

Have you tried?

**Comment by gbowne1** [comment]
I did manage to fix the login.html which works fine.  If you load login.html through a preview it works now.  I also added the missing .js files called out in the body of the login.html but they are kinda incomplete.

**Comment by jzunigarce** [comment]
I've been doing some basic tests and everything works fine, I returned some responses from the routes

**Comment by gbowne1** [comment]
Cool. Yeah, I was able to see routes too.  We will have to send cors headers in the routes too.  I have the code we will need for that.. the browser will go nuts in console.

In the old project the login page (now login.htm) loaded at / till you logged in and or registered. At which point it would go as a redirect to either profile or dashboard, but some routes failed. Just depended on a few things.

Im going to add the components pages in public for each of the routes tomorrow.

**Comment by jzunigarce** [comment]
Will you use jwt token or sessions for authentication?

**Comment by gbowne1** [comment]
We have both options available.  I am ok with either option.  I would like to leverage both the server and the browser.

I prefer jwt.  Its already installed, so is cookie and body parser and axios (axios to both sides if you noticed.)

We can send both cookies and tokens.

We arent using external auth like google to log in.

External APIs like from radioreference.com might need some auth too and in fact that API need its own token.

We are bringing in a bunch of external APIs depending on where you are in the app.

**Comment by gbowne1** [comment]
Added a pile of more stuff today.  @jzunigarce including all of the HTML pages in the /src/client/public 

I worked on getting the res.send's in the routes for the pages for a few of the items.

Now just gotta get a bunch of stuff wired up.

**Comment by jzunigarce** [comment]
Can I separate the routes in another folder?

**Comment by gbowne1** [comment]
yeah you can. @jzunigarce 

something like?

```ascii
└── src
    ├── client
    │   ├── css
    │   ├── js
    │   └── index.html
    └── server
        ├── routes
        │   ├── index.js
        │   └── users.js
        └── server.js
```

Then I guess you could:

const indexRoutes = require('./routes/index');
const userRoutes = require('./routes/users');

app.use('/', indexRoutes);
app.use('/users', userRoutes);

or whatever... just let me push up a couple changes I flubbed on today.

**Comment by gbowne1** [comment]
You should save server logs into /src/server/logs.. that needs wired up too.  .gitignore is set to ignore them.  for obv reasons. but theres a couple packages we have now for logging.

**Comment by jzunigarce** [comment]
@gbowne1 What routes will you implement and what methods (post, get, put, delete, etc)?

**Comment by gbowne1** [comment]
Lets start with get and post.  As we wire up the app, we can decide.  

My inital goal is getting the dashboard and login and signup all wired in everywhere, server, routes, db, auth, etc.. etc.. 

I put in the routes in server.js that I had in my old project

**Comment by gbowne1** [comment]
I think we might also need const http = require('http'); at some point.

**Comment by jzunigarce** [comment]
What will you do with the http module?

**Comment by gbowne1** [comment]
not sure. Just a thought. We are already doing a lot of things with the server at this point. I dont know if it will solve any particular issues.

Can you have a look through the PR? Would you like to be added as a collaborator?

**Comment by jzunigarce** [comment]
For now I consider that it will not be necessary to use it, since we are using express. Of course I would like to be a collaborator. I will upload a PR, although it still has a detail with the external images, CSP details. I will work to correct it.

**Comment by gbowne1** [comment]
Merged, btw.  Yeah it probabky wont be needed.. just know its there.  

We still need logging, etc.  Nodemon logs are ok.. but not terribly granular. 

I still get 505 in Nodemon. when I have a React app I am working on run on 3000 at times.  It really should ask you if you want the next available port if somethings already on 3000.  

I think a backend start script might help out too.

**Comment by jzunigarce** [comment]
We can use docker or I can set the .env to set the PORT of the server

**Comment by jzunigarce** [comment]
Can you delete the issues that have already been resolved to avoid accumulation?

**Comment by gbowne1** [comment]
Yeah am working on doing that some atm.  

We can move some to discussion that need further clarification, etc.  

Dockerization might help.  I was going to wait for that.

There is a port set in .env already.  Its 3000.  But its not forwarding to a new port if theres already one in use.  React dev server does that.  You just push y or type yes and enter and it goes to 3001 or whatever is next.

**Comment by gbowne1** [comment]
I was reading that you could set bin/www but it requires http.

**Comment by gbowne1** [comment]
Users will get their own user profile too.

We can use app.js I created on both sides to run as a controller.. one does DOM stuff on the client.  The other app.js acts as a engine on top of express, node and the db.  

I added more of the json data.

We still have at least one external API to consume and will likely provide our own.  FCC lisence records to help with records in the DB.  You type in a callsign  and it could auto populate some fields??

**Comment by gbowne1** [comment]
Re-naming this issue as a [TODO] TODO, but expect a TODO.md file with actual TODOs to avoid 'Issues' collecting issues..

**Comment by gbowne1** [comment]
TODO.md pushed.  If you have VSCode and a TODO tracker extension it should pick up the file.

**Comment by gbowne1** [comment]
This page:

![Screenshot 2023-04-23 at 15-17-22 Base Index](https://user-images.githubusercontent.com/47549872/233869096-e229fa10-0293-4a34-a417-7f592cd5400f.png)

which loads at: `/`

Ideally should be a splash/cover page (/src/client/public/index.html) called by either the server side app.js by linking the app.js && index.js in the html.  The app.js will have DOM stuff built as a controller.  It would have a button, page spinner or load progress indicator, photo and an app title.  The very next page you would see is the /login which loads login.html.  The next page would be /dashboard.

**Comment by gbowne1** [comment]
I tested login, register, reset password  with some typical credentials.. it's not really working.  :-1: :disappointed:

**Comment by jzunigarce** [comment]
We need fix all routes, Do you think that I work with the refactoring of the routes?

**Comment by gbowne1** [comment]
fine with me.

**Comment by jzunigarce** [comment]
We need define a route for "/", we currently do not have a defined route

**Comment by gbowne1** [comment]
Yep.  The page would the one at /src/client/public/index.html in the tree.

**Comment by gbowne1** [comment]
An example of what I had in mind for the off canvas drawer.
![Screenshot 2021-08-19 at 20-19-17 React App](https://user-images.githubusercontent.com/47549872/233870315-f0d751cc-37fa-4346-b2fd-b2fd02b4ea24.png)

**Comment by gbowne1** [comment]
@jzunigarce I fixed up the page that loads at localhost:3000 or /  it needs an image, etc. but should be good

This is what you should see when the app loads.  The next page should be /login then /dashboard then possibly /profile if the user has not created one.  

You should be able to get to /login by clicking on the button unless there is a better idea.  Ideally it should have some loader spinner, progress bar, etc.

**Comment by gbowne1** [comment]
What I noticed now is that the login doesn't work. Didn't seem to work before now but perhaps some more stuff needs wired up.  So, entering creds like testuser@example.com and a hashable password and clicking Login doesn't progress the login to the next stage.

**Comment by gbowne1** [comment]
New screen for root /

![Screenshot 2023-04-24 at 18-27-37 My Website](https://user-images.githubusercontent.com/47549872/234152378-56f8c2af-95c7-4ede-b438-391e8e7010b2.png)

**Comment by jzunigarce** [comment]
After logging in, which page should i go to?

**Comment by jzunigarce** [comment]
After logging, which page should i go to?

**Comment by jzunigarce** [comment]
Today i work login in backend

**Comment by gbowne1** [comment]
/dashboard should totally be the next page in the process.  But, ideally if the user is not a returning user, should go to a profile creating page.  If a returning user should be just /dasbhoard.

**Comment by gbowne1** [comment]
I got some work done on a profile page.. Might get some of that done.

**Comment by gbowne1** [comment]
Pushed up the initial work for the profile.  Both the index.html and profile need some work.  There are some errors in console, but otherwise work.  Now just needs routes, more CSS work, etc.

**Comment by gbowne1** [comment]
I wasnt sure where to put the button on the index.html.

**Comment by jzunigarce** [comment]
Are you have a mockup of project?

**Comment by gbowne1** [comment]
No, I do not have a mockup.  I have screenshots of various iterations I tried out.

**Comment by gbowne1** [comment]
I think we already have about 90-95% of what will be needed just need cleaned up a bit and actually working.

Including the HTML pages, CSS.. cleaning up and debugging the js.. etc.  Traditionally I have not needed mockups anyhow.. especially in community driven development.  Typically people come up with much better designs than I do.

**Comment by gbowne1** [comment]
using the signUp.js I did get this message in console.. maybe it partially works??

User registered: 
Object { username: "testuser", email: "testuser1@example.com", password: "Testpass1!" }

**Comment by jzunigarce** [comment]
Maybe it would be useful to also store the user's email

**Comment by gbowne1** [comment]
yeah.  I am getting a Uncaught ReferenceError: checkpass is not defined error from formEvents.js though.  (also while still navigated to /signin.. but using the signup function)

**Comment by gbowne1** [comment]
@jzunigarce I am gonna work on the dashboard a bit today.

The click event listener on the index.html isnt working

Ive been trying random things on dashboard.html to get the cards in two rows of 4 or 5 cards.  I think it needs a row/col setup in Bootstrap.

Let me know if there are any TODOs in the TODO.md you think we should open up issues for.

**Comment by jzunigarce** [comment]
Have you tried using css grid?

**Comment by gbowne1** [comment]
Not on this particular page of the project.

**Comment by gbowne1** [comment]
I see the issue.  I didnt use d-flex mx-* my-* etc properly.

**Comment by gbowne1** [comment]
yeah, this was totally my fault.  using the wrong Bootstrap 5 classes.  Flex works good on this, although it would work with Grid too.  Grid might be better for this but, all I had to do was adjust the positions and margins.  My bad.

How should we go about adding /profile route? It's accessible by the Profile in the user menu.  I wanna make this a modal.

I will push up what I have in a bit.

**Comment by gbowne1** [comment]
Pushed up the changes I made.  Dashboard looks better, though not perfect.  Still some minor adjustment to be done.

**Comment by gbowne1** [comment]
Its not letting me hav access to a few of the images. Am working on changing dashboard links, text and images to the proper ones.

**Comment by gbowne1** [comment]
Pictures need a bit of sizing help and dashboard needs routing for the individual pages, like /vhflog, /scanlog, /mwlog, /hamlog, /qsldb 

I would like to extract the navbar as its own component. I think thats about all the initial reusability we will need to start with, other than the sidenav.

Most of the form pages need fixing starting with the navbar so it looks the same as the dashboard navbar.

Navbar in  there is still missing fa-bars on the far left to open the drawer.

**Comment by gbowne1** [comment]
I am going to add some boilerplate login, resetpassword and register tests for mocha/cha this evening.  Will need to add one for authentication/authorization.  

Am still learning both so I added what I could.

**Comment by gbowne1** [comment]
@jzunigarce I went and fixed password reset POST inside the server.js but now it requires a ./user

Not sure of what to do here.

**Comment by gbowne1** [comment]
ahh.. the fix was just changing the User required route to ./models/user server restarted fine.  Pushing fix.

**Comment by gbowne1** [comment]
I couldnt get the tests I added to work, but they are there so we can hack them out so they work.

**Comment by gbowne1** [comment]
At some point we should move to Ecmascript 2021 but by then we should probably install prop-types or typescript.  that way we can use import syntax instead of constants, vars, etc.

**Comment by gbowne1** [comment]
@jzunigarce I am going to add some UI / UX issues tonight.
